dist: trusty
addons:
  sonarcloud:
    organization: imrafaelmerino
    token:
      secure: jQKLave7CwZLA9js1+LmW25xsp5I9w7ta+n/iDuuKescdT7l2C4/6DGig8zI6b/mpWFJO7Lc2d9oBNBbL4+m/X165VjhT/FgQ2WJHHF6LUqBOcFzfN+oMxKFKjlqR89H6Uamkfj+x12HfuHJlJZM07fd11SCsHzjbc7b9RvIasRftz4bdM7nfkny9SK9LT+/GjBc8nVx94fJ03fgam92/2o6EVDKv0i9ssVOKYDpQHhJBt9d1VHsmygDXGcDn/AYllwLihDThH94cEeOZNsyl/Hi38V0BjNrzqTJVTpZIXNWiVVdOteuEfUyiodSSaYx3YJ+8uYEj1EBYrir4HMbF1sCf3m5qWRUobX8bZZQQo283YUXedlyrclqlS4VdiyHjLB+RUPbN9zt6mpj8AYvAvM45WYSCz58aIKhj0EBU2wK355sDcUwAx6hrU5jcobzw4+4b/MlPMfKwuIg41ohL0D2RiZt0g8O/3/yIGEsnRkCNpMfrUGq5bQcpWGwxjYSvpRN1teZyGqkteOE+d0Xx79HLq6Hx3uptlvvnF/l7Yd/t9KX+b9jpV4711lp0u7rAPCbFlewOe+c275hbi1u6Owu1U2r0q3Daz98qMLtN08JRGPbuuSawU4ACQDkVAlDNyvjSG2VO4PDsh3PXeeyIzCT82QsQkVdPFqlRQPvtM4=
script:
- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  script: sbt publishSigned
  skip_cleanup: true
  on:
    repo: imrafaelmerino/json-scala-values
    tags: true
- api_key: "$GITHUB_TOKEN"
  body: 'Generated by TravisCI during the release process: build URL: $TRAVIS_BUILD_WEB_URL,
    build number: $TRAVIS_BUILD_NUMBER, commit: $TRAVIS_COMMIT, tag: $TRAVIS_TAG'
  draft: true
  file:
  - docs/README.md
  - docs/index.md
  name: Prueba
  prerelease: true
  provider: releases
  skip_cleanup: true
  on:
    repo: imrafaelmerino/json-scala-values
    tags: true
language: scala
scala: 2.13.0
env:
  global:
    secure: Bibhj/qGkShnp91I+6mZ7wjwPd4UkSIGArxFuQWswocZ8/IjTolgywtowt5rjeHbuhhxMV2DYo6x86//KB6lW0BV/EtwDZnMS2FyIwuBcJU54R8mhi1NlSP4rqnpHrkZ79DBkFK3G5g0zXiGMRNxx2fn8wGTWbuuuRyd8P15YiVD4bGHLYbk0ehMkFVPkseHSA5ssksCfo9bBA13RyuAiazpyZJHDsW9dlUcg9EacYyjPmOvt+VdD8LLXTSV+GbruaptMVJlOVqULvS2jVo8c/DT/an6jYwkJZzf1Vsji5WOPEvhR0+Xz/mT1Z1oun23nJ0vdZEarIFTNo2ipjqBFBh2YkVeeIQ3ASgY0bpoWKDCtQRYXLA0yaenmcLemGWd21Sy5wdWqdgvNSP3v76LFQHs8XxCtDqI+OIwo24K0jFWNvvB1pNmojdtNMrleRgivIDzDzSmPpXkl3CdmTDpxbi/SpaJkRIhklRsLzDT5lr68B0YQJk5bVEfgsCoMDjM4XvpLmY3B9LlfIWOihZM2WUNFk+oh+KhBSixm0F2ueXG1IRjxRegW52zXxxTyqLPYPNj0pQQpqCa8mCceKxBSaLWSP8t16MEXKAxOtccsBClVDAMcLLIIN3d8KVD5QArwOe4VwVJNFb19GbnZasgtJPDk1I34tX4dBCQk78kklA=
before_install:
- openssl aes-256-cbc -K $encrypted_4ddfc74946a5_key -iv $encrypted_4ddfc74946a5_iv
  -in secret-key.asc.enc -out secret-key.asc -d
- echo $PGP_PASSPHRASE | gpg --passphrase-fd 0 --batch --yes --import secret-key.asc

