dist: trusty
addons:
  sonarcloud:
    organization: imrafaelmerino
    token:
      secure: jQKLave7CwZLA9js1+LmW25xsp5I9w7ta+n/iDuuKescdT7l2C4/6DGig8zI6b/mpWFJO7Lc2d9oBNBbL4+m/X165VjhT/FgQ2WJHHF6LUqBOcFzfN+oMxKFKjlqR89H6Uamkfj+x12HfuHJlJZM07fd11SCsHzjbc7b9RvIasRftz4bdM7nfkny9SK9LT+/GjBc8nVx94fJ03fgam92/2o6EVDKv0i9ssVOKYDpQHhJBt9d1VHsmygDXGcDn/AYllwLihDThH94cEeOZNsyl/Hi38V0BjNrzqTJVTpZIXNWiVVdOteuEfUyiodSSaYx3YJ+8uYEj1EBYrir4HMbF1sCf3m5qWRUobX8bZZQQo283YUXedlyrclqlS4VdiyHjLB+RUPbN9zt6mpj8AYvAvM45WYSCz58aIKhj0EBU2wK355sDcUwAx6hrU5jcobzw4+4b/MlPMfKwuIg41ohL0D2RiZt0g8O/3/yIGEsnRkCNpMfrUGq5bQcpWGwxjYSvpRN1teZyGqkteOE+d0Xx79HLq6Hx3uptlvvnF/l7Yd/t9KX+b9jpV4711lp0u7rAPCbFlewOe+c275hbi1u6Owu1U2r0q3Daz98qMLtN08JRGPbuuSawU4ACQDkVAlDNyvjSG2VO4PDsh3PXeeyIzCT82QsQkVdPFqlRQPvtM4=
script:
  - sbt clean jacoco
after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  script: sbt -DNEXUS_PASSWORD=$NEXUS_PASSWORD -DNEXUS_USERNAME=$NEXUS_USERNAME publishSigned sonatypeRelease
  skip_cleanup: true
  on:
    repo: imrafaelmerino/json-scala-values
    tags: true
- api_key: "$GITHUB_TOKEN"
  body: 'Generated by TravisCI during the release process: build URL: $TRAVIS_BUILD_WEB_URL,
    build number: $TRAVIS_BUILD_NUMBER, commit: $TRAVIS_COMMIT, tag: $TRAVIS_TAG'
  draft: false
  file:
  - docs/README.md
  - docs/index.md
  - docs/CHANGELOG.md
  name: Rufus (Dotty)
  prerelease: false
  provider: releases
  skip_cleanup: false
  on:
    repo: imrafaelmerino/json-scala-values
    tags: true
language: scala
before_install:
- openssl aes-256-cbc -K $encrypted_4ddfc74946a5_key -iv $encrypted_4ddfc74946a5_iv -in secret-key.asc.enc -out secret-key.asc -d
- echo $PGP_PASSPHRASE | gpg --passphrase-fd 0 --batch --yes --import secret-key.asc

